# -*- coding: utf-8 -*-
"""submission_2MLT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLb6qNxydJ81j6yYKMcEHBINBuvBKWeF

# Sistem Rekomendasi Makanan

## 1. Menginstall library yg dibutuhkan
"""

!pip install opendatasets

"""## 2. Mengunduh dataset"""

import opendatasets as od
od.download('https://www.kaggle.com/datasets/schemersays/food-recommendation-system')

"""## 3. Menyiapkan library"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Library untuk content-based filtering
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Library untuk collaborative filtering
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import ReduceLROnPlateau

import warnings
warnings.filterwarnings("ignore")

"""# **4. Data Understanding**

### 4.1 Membaca dataset makanan dan rating
"""

df_makanan = pd.read_csv('/content/food-recommendation-system/1662574418893344.csv')
df_rating = pd.read_csv('/content/food-recommendation-system/ratings.csv')

print(df_makanan.head(3))
print("<=================>")
print(df_makanan.shape)
print("<=================>")
df_makanan.info()

"""Dari sel kode di atas, dapat dilihat bahwa dataset makanan memiliki 400 baris dengan 5 kolom.

### 4.2 Cek kategori makanan unik
"""

print(len(df_makanan['C_Type'].unique()))
print(df_makanan['C_Type'].unique())

"""Dari sel kode di atas, dapat dilihat bahwa ada 16 jenis makanan yang berbeda di dalam dataset. Namun, terlihat bahwa makanan Korea memiliki dua nilai unik yang harus dikoreksi terlebih dahulu. Jadi, sel kode di bawah ini digunakan untuk mengoreksi yang satu ini.

### 4.3 Membersihkan nama kategori
"""

df_makanan['C_Type'] = df_makanan['C_Type'].replace([' Korean'], 'Korean')
print(len(df_makanan['C_Type'].unique()))
print(df_makanan['C_Type'].unique())

"""### 4.4 Distribusi kategori"""

df_makanan['C_Type'].value_counts().sort_values().plot(kind='barh')

"""Sel kode di atas adalah plot distribusi data jenis makanan. Dari plot tersebut, dapat dilihat bahwa jenis makanan yang paling dominan adalah makanan India, diikuti oleh makanan sehat dan makanan penutup."""

print(df_rating.head(3))
print("<=================>")
print(df_rating.shape)
print("<=================>")
df_rating.info()

print('Jumlah User_ID:', len(df_rating['User_ID'].unique()))
print("<=================>")
print('Jumlah Food_ID:', len(df_rating['Food_ID'].unique()))
print("<=================>")
print(df_rating.describe())

sns.displot(df_rating['Rating'], kde=True, bins=10)

"""Sel kode di atas adalah tentang plot distribusi data tentang rating. Dari plot ini, dapat dilihat bahwa distribusi rating cenderung berada di sekitar angka 3, 5, dan 10.

# **5. Data Preprocessing**

### 5.1 Menggabungkan Data
"""

df_gabungan = pd.merge(df_rating, df_makanan[['Food_ID', 'Name', 'C_Type']], on='Food_ID', how='left')
print(df_gabungan.head())
print(df_gabungan.isnull().sum())
df_gabungan = df_gabungan.dropna()

df_rating = df_rating.dropna()

"""### 5.2 Urutkan berdasarkan Food_ID"""

df_urut = df_gabungan.sort_values('Food_ID', ascending=True)
print(df_urut.head())
print(len(df_urut['Food_ID'].unique()))
print(df_urut['C_Type'].unique())

"""### 5.3 Persiapan data makanan tanpa duplikasi"""

df_prep = df_urut.sort_values('Food_ID').drop_duplicates('Food_ID')
df_prep.loc[df_prep['C_Type'] == 'Healthy Food', 'C_Type'] = 'Healthy_Food'

"""
### 5.4 Ekstraksi kolom untuk content-based filtering"""

list_id = df_prep['Food_ID'].tolist()
list_nama = df_prep['Name'].tolist()
list_kategori = df_prep['C_Type'].tolist()

print(len(list_id), len(list_nama), len(list_kategori))

"""Sel kode di atas digunakan untuk mengubah seri `Food_ID`, `Nama`, dan `C_Type` menjadi list.

### 5.5 Membuat dataframe baru
"""

df_makanan_baru = pd.DataFrame({
    'id': list_id,
    'food_name': list_nama,
    'category': list_kategori
})

print(df_makanan_baru.head())
print(df_makanan_baru.sample(5))

"""# **6. Modeling**

### 6.1 Content-Based Filtering

##### 6.1.1 Membuat TF-IDF vectorizer berdasarkan kategori makanan
"""

tfidf_vect = TfidfVectorizer()
tfidf_vect.fit(df_makanan_baru['category'])
print(tfidf_vect.get_feature_names_out())

tfidf_matrix = tfidf_vect.fit_transform(df_makanan_baru['category'])
print(tfidf_matrix.shape)
print(tfidf_matrix.todense())

"""Sel kode di atas digunakan untuk mengubah vektor tf-idf menjadi matriks menggunakan fungsi todense().

##### 6.1.2 Menampilkan beberapa contoh fitur
"""

df_tfidf = pd.DataFrame(tfidf_matrix.todense(),
                        columns=tfidf_vect.get_feature_names_out(),
                        index=df_makanan_baru['food_name'])
print(df_tfidf.sample(11, axis=1).sample(10, axis=0))

"""##### 6.1.3 Matriks cosine similarity

"""

cos_sim = cosine_similarity(tfidf_matrix)
df_cosine = pd.DataFrame(cos_sim, index=df_makanan_baru['food_name'], columns=df_makanan_baru['food_name'])
print('Shape:', df_cosine.shape)
print(df_cosine.sample(5, axis=1).sample(10, axis=0))

def rekomendasi_makanan(nama_makanan, sim_data=df_cosine, items=df_makanan_baru[['food_name', 'category']], top=5):
    # Mengambil indeks kemiripan
    idx_array = sim_data.loc[:, nama_makanan].to_numpy().argpartition(range(-1, -top, -1))
    rekomendasi = sim_data.columns[idx_array[-1:-(top+2):-1]]
    rekomendasi = rekomendasi.drop(nama_makanan, errors='ignore')
    return pd.DataFrame(rekomendasi).merge(items).head(top)

"""Kode program di atas digunakan untuk membuat sebuah fungsi yang dapat digunakan untuk memberikan rekomendasi makanan dengan input berupa nama makanan. Fungsi ini pertama-tama akan mengambil data dengan menggunakan argpartition untuk mempartisi secara tidak langsung di sepanjang sumbu yang diberikan, mengambil data dengan kemiripan terbesar dari indeks yang ada, dan membuang `food_name` agar nama makanan yang dicari tidak muncul dalam hasil rekomendasi."""

print(df_makanan_baru[df_makanan_baru['food_name'] == 'banana chips'])
print(rekomendasi_makanan('banana chips'))

"""The output of the code cell above shows the food recommendation results. It can be seen that the function outputs 5 food names that have the same category as the food name that has been inputted before, that is Snack category.

### 6.2 Collaborative Filtering

##### 6.2.1 Encoding User_ID dan Food_ID
"""

user_list = df_rating['User_ID'].unique().tolist()
print('User_ID list:', user_list)

user2idx = {user: idx for idx, user in enumerate(user_list)}
idx2user = {idx: user for idx, user in enumerate(user_list)}
print('Mapping User_ID:', user2idx)
print('Mapping indeks ke User_ID:', idx2user)

food_list = df_rating['Food_ID'].unique().tolist()
food2idx = {food: idx for idx, food in enumerate(food_list)}
idx2food = {idx: food for idx, food in enumerate(food_list)}

"""##### 6.2.2 Menambahkan kolom encoding pada dataframe rating"""

df_rating['user'] = df_rating['User_ID'].map(user2idx)
df_rating['food'] = df_rating['Food_ID'].map(food2idx)

n_users = len(user2idx)
n_foods = len(idx2food)
print(n_users, n_foods)

df_rating['rating'] = df_rating['Rating'].astype(np.float32)
min_rat = df_rating['rating'].min()
max_rat = df_rating['rating'].max()
print('Jumlah User: {}, Jumlah Food: {}, Rating Min: {}, Rating Max: {}'.format(n_users, n_foods, min_rat, max_rat))

"""Sel kode di atas digunakan untuk memeriksa jumlah pengguna, jumlah makanan, dan nilai minimum serta maksimum rating yang tersedia pada dataset."""

df_rating = df_rating.sample(frac=1, random_state=42)

"""##### 6.2.3 Menyiapkan data untuk training"""

X_data = df_rating[['user', 'food']].values
y_data = df_rating['rating'].apply(lambda x: (x - min_rat) / (max_rat - min_rat)).values

split_index = int(0.8 * df_rating.shape[0])
X_train, X_val = X_data[:split_index], X_data[split_index:]
y_train, y_val = y_data[:split_index], y_data[split_index:]
print(X_data, y_data)

"""Sel kode di atas digunakan untuk membuat variabel `x` dan `y`, diikuti dengan pemisahan data.

##### 6.2.4 Membangun model rekomendasi dengan TensorFlow
"""

class RecommenderModel(tf.keras.Model):
    def __init__(self, total_users, total_foods, embed_size, **kwargs):
        super(RecommenderModel, self).__init__(**kwargs)
        self.user_embed = layers.Embedding(total_users, embed_size,
                                           embeddings_initializer='he_normal',
                                           embeddings_regularizer=keras.regularizers.l2(1e-6))
        self.user_bias = layers.Embedding(total_users, 1)
        self.food_embed = layers.Embedding(total_foods, embed_size,
                                           embeddings_initializer='he_normal',
                                           embeddings_regularizer=keras.regularizers.l2(1e-6))
        self.food_bias = layers.Embedding(total_foods, 1)

    def call(self, inputs):
        u_vec = self.user_embed(inputs[:, 0])
        u_bias = self.user_bias(inputs[:, 0])
        f_vec = self.food_embed(inputs[:, 1])
        f_bias = self.food_bias(inputs[:, 1])

        dot = tf.reduce_sum(u_vec * f_vec, axis=1, keepdims=True)
        x_out = dot + u_bias + f_bias
        return tf.nn.sigmoid(x_out)

"""Sel kode di atas digunakan untuk membuat kelas RecommenderModel dengan kelas Model keras."""

model_reco = RecommenderModel(n_users, n_foods, 50)
model_reco.compile(loss=tf.keras.losses.BinaryCrossentropy(),
                   optimizer=keras.optimizers.Adam(learning_rate=0.0001),
                   metrics=[tf.keras.metrics.RootMeanSquaredError()])

"""Sel kode di atas digunakan untuk menyusun model. Model ini menggunakan Binary Crossentropy untuk menghitung fungsi kerugian, Adam (Adaptive Moment Estimation) sebagai pengoptimal, dan Root Mean Squared Error (RMSE) sebagai metrik evaluasi."""

history = model_reco.fit(X_train, y_train, batch_size=9, epochs=50, validation_data=(X_val, y_val))

plt.plot(history.history['root_mean_squared_error'])
plt.plot(history.history['val_root_mean_squared_error'])
plt.title('model_metrics')
plt.ylabel('root_mean_squared_error')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='best')
plt.show()

"""Dari visualisasi metrik pada output code cell di atas, dapat dilihat bahwa terjadi tren penurunan RMSE pada setiap epoch baik pada data training maupun data evaluasi. Hal ini mengindikasikan bahwa model dapat belajar dengan baik dari data. Dari visualisasi ini juga dapat dilihat bahwa diperoleh nilai error akhir sebesar 0.0.2623 dengan error pada data validasi sebesar 0.3264.

##### 6.2.5 Mengambil data sample rating
"""

df_sample = pd.read_csv('/content/food-recommendation-system/ratings.csv')
sample_user = df_sample['User_ID'].sample(1).iloc[0]
user_ratings = df_sample[df_sample['User_ID'] == sample_user]

"""Mengambil makanan yang belum pernah dicoba oleh user"""

makanan_belum = df_makanan_baru[~df_makanan_baru['id'].isin(user_ratings['Food_ID'].values)]['id']
makanan_belum = list(set(makanan_belum).intersection(set(food2idx.keys())))
makanan_belum_idx = [[food2idx[x]] for x in makanan_belum]

user_encoded = user2idx[sample_user]
user_food_pairs = np.hstack((np.full((len(makanan_belum_idx), 1), user_encoded), makanan_belum_idx))
prediksi_rating = model_reco.predict(user_food_pairs).flatten()

"""Mengambil 10 rekomendasi teratas"""

top_indices = prediksi_rating.argsort()[-10:][::-1]
rekomendasi_ids = [idx2food[makanan_belum_idx[i][0]] for i in top_indices]

print('Rekomendasi untuk User:', int(sample_user))
print('---' * 10)
print('Makanan yang pernah dinilai tinggi oleh user:')
top_user = user_ratings.sort_values(by='Rating', ascending=False).head(5)['Food_ID'].values
for row in df_makanan_baru[df_makanan_baru['id'].isin(top_user)].itertuples():
    print(row.food_name, ":", row.category)

print('---' * 10)
print('Top 10 rekomendasi makanan:')
for row in df_makanan_baru[df_makanan_baru['id'].isin(rekomendasi_ids)].itertuples():
    print(row.food_name, ":", row.category)

"""Sel kode di atas melakukan rekomendasi makanan untuk pengguna dengan `User_ID` 6. Dari outputnya, dapat dilihat bahwa ada 10 makanan yang direkomendasikan untuk pengguna ini."""